"""Add DynamicDataEntry model for custom device data reporting

Revision ID: d8bac763c5ad
Revises: e9115264bd24
Create Date: 2025-06-01 11:42:51.394223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bac763c5ad'
down_revision = 'e9115264bd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_data_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('task_assignment_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('data_payload', sa.JSON(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['task_assignment_id'], ['task_assignment.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamic_data_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_data_entry_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dynamic_data_entry_reported_at'), ['reported_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_data_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_data_entry_reported_at'))
        batch_op.drop_index(batch_op.f('ix_dynamic_data_entry_data_type'))

    op.drop_table('dynamic_data_entry')
    # ### end Alembic commands ###
