"""Add Tenant and User models, add tenant_id to Device and TaskDefinition

Revision ID: e9115264bd24
Revises: b2912ec7109b
Create Date: 2025-06-01 11:32:11.795084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9115264bd24'
down_revision = 'b2912ec7109b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_user_tenant_id'), # Added name here too for consistency
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_device_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_taskdefinition_tenant_name', ['name', 'tenant_id'])
        batch_op.create_foreign_key('fk_task_definition_tenant_id', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_definition', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_definition_tenant_id', type_='foreignkey')
        batch_op.drop_constraint('uq_taskdefinition_tenant_name', type_='unique')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('user')
    op.drop_table('tenant')
    # ### end Alembic commands ###
